const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Plugins.shadowlight,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.Tilemap.Exps.TilesJSON,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Exps.NodeXAt,
		C3.Behaviors.Pathfinding.Exps.NodeCount,
		C3.Behaviors.Pathfinding.Exps.NodeYAt,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Pathfinding.Acts.ClearObstacles,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.LOS.Acts.SetCone,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.MoveTo.Acts.MoveToObject
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{MoveTo: 0},
	{title1: 0},
	{Dhurandar_title: 0},
	{index: 0},
	{bullets: 0},
	{AJAX: 0},
	{BulletsPosition: 0},
	{Browser: 0},
	{Audio: 0},
	{Txt_Loading: 0},
	{jio_studio: 0},
	{b62: 0},
	{Sine: 0},
	{loading_dots: 0},
	{Txt_TapToStart: 0},
	{Touch: 0},
	{Solid: 0},
	{ShadowCaster: 0},
	{MapFloor: 0},
	{Pathfinding: 0},
	{BoundToLayout: 0},
	{Player_Idel: 0},
	{"8Direction": 0},
	{Player_Walk: 0},
	{pathLine: 0},
	{Created: 0},
	{Tween: 0},
	{walkingTile: 0},
	{PathArray: 0},
	{Blade: 0},
	{BladeSmoother: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{SoldireBlue: 0},
	{LineOfSight: 0},
	{Enemy1: 0},
	{Pin: 0},
	{ShadowLight: 0},
	{FOV: 0},
	{MapFloor2: 0},
	{Caster: 0},
	{bullet_index: 0},
	{Splash_State: 0},
	{TargetX: 0},
	{TargetY: 0},
	{PreviousX: 0},
	{TileWidth: 0},
	{TileHeight: 0},
	{PreviousY: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	title1: class extends self.ISpriteInstance {},
	Dhurandar_title: class extends self.ISpriteInstance {},
	bullets: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	BulletsPosition: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Txt_Loading: class extends self.ITextInstance {},
	jio_studio: class extends self.ISpriteInstance {},
	b62: class extends self.ISpriteInstance {},
	loading_dots: class extends self.ISpriteInstance {},
	Txt_TapToStart: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	MapFloor: class extends self.ITilemapInstance {},
	Player_Idel: class extends self.ISpriteInstance {},
	Player_Walk: class extends self.ISpriteInstance {},
	pathLine: class extends self.ISpriteInstance {},
	walkingTile: class extends self.ISpriteInstance {},
	PathArray: class extends self.IArrayInstance {},
	Blade: class extends self.ISpriteInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	SoldireBlue: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	FOV: class extends self.ISpriteInstance {},
	MapFloor2: class extends self.ITilemapInstance {},
	Caster: class extends self.ISpriteInstance {}
}